export const tagTypes = {
  user: "user",
  member: "member",
  agency: "agency",
  committee: "committee",
  blog: "blog",
  job: "job",
  news: "news",
  event: "event",
  banner: "banner",
  gallery: "gallery",
  certification: "certification",
  payment: "payment",
  consultation: "consultation",
  scholarship: "scholarship",
};

export const tagTypesList = [
  tagTypes.member,
  tagTypes.user,
  tagTypes.agency,
  tagTypes.committee,
  tagTypes.blog,
  tagTypes.job,
  tagTypes.news,
  tagTypes.event,
  tagTypes.banner,
  tagTypes.gallery,
  tagTypes.certification,
  tagTypes.payment,
  tagTypes.consultation,
  tagTypes.scholarship,
];
